name: track-scoreboard
run-name: Track scoreboard

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: get-scoreboard
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls -a
          git pull
          python3 tools/api.py scoreboard
          git config user.name  "Cron"
          git config user.email "github@peria.jp"
          git add data/scoreboard
          git commit -m 'Update score board'
          git push
