name: track-scoreboard
run-name: Track scoreboard

# Tracked during the contest.

# on:
#  schedule:
#     - cron: '*/5 * * * *'

jobs:
  build:
    name: get-scoreboard
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: actions/checkout@v3
      - name: Hand Prepare
        run: |
          git config user.name  "Cron"
          git config user.email "github@peria.jp"
          git config -l
          pip install python-dateutil
      - name: get-scoreboard
        run: |
          python3 tools/api.py scoreboard
      - name: commit
        run: |
          git add data/scoreboard
          git commit -m 'Update score board'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}